name: PR Flow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions: {}

jobs:

  lint:
    uses: ./.github/workflows/_reusable_pr_lint.yml

  test-node-actions:
    uses: ./.github/workflows/_reusable_pr_test_node.yml

  test-python-actions:
    uses: ./.github/workflows/_reusable_pr_test_python.yml
